apiVersion: v1
kind: Service
metadata:
  name: source-scan-service
  labels:
    app: ssd
    component: source-scan
{{ include "ssd.standard-labels" . | indent 4 }}
{{- if .Values.sourcescan.serviceAnnotations }}
  annotations:
{{ toYaml .Values.sourcescan.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  ports:
    - name: source-scan
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: ssd
    component: source-scan
