# Need to check in Saml and dex use case
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "ssd-initial-password") -}}
{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: ssd-initial-password
type: Opaque
data:
  ADMIN_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  USER1_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: ssd-initial-password
type: Opaque
data:
  ADMIN_PASSWORD: {{ $existingSecret.data.ADMIN_PASSWORD }}
  USER1_PASSWORD: {{ $existingSecret.data.USER1_PASSWORD }}
{{- end }}

