apiVersion: v1
kind: Service
metadata:
  name: ssd-audit-service
  labels:
    app: ssd
    component: ssd-audit-service
spec:
  selector:
    app: ssd
    component: ssd-audit-service
{{ include "ssd.standard-labels" . | indent 4 }}
{{- if .Values.ssdauditservice.serviceAnnotations }}
  annotations:
{{ toYaml .Values.ssdauditservice.serviceAnnotations | indent 4 }}
{{- end }}
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
      {{- if eq .Values.k8sServiceType "NodePort" }}
      nodePort: 50051
      {{- end }}
