apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd-license-generator-data
  labels:
    app: ssd
    component: license-generator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.licensegenerator.storageMountSize }}
  {{- if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass }}
  {{- end -}}
  
