{{- if and (eq .Values.installationMode "ArgoCD") .Release.IsInstall -}}
apiVersion: v1
kind: Secret
metadata:
  name: mobsf-secret
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
data:
  mobsfapikey: {{ randAlphaNum 62 | b64enc | quote }}
{{- end }}
