{{- if and (eq .Values.installationMode "ArgoCD") .Release.IsInstall -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-binding
subjects:
  - kind: ServiceAccount
    name: secrets-sa
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: secrets-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: secret-creator
          image: quay.io/opsmxpublic/opsmx-custom-binaries:kubectl-spin-cli-git-bash-jq-yq
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /bin/bash
            - -c
            - |
              set -e

              {{- if .Values.db.enabled }}
              echo "Generating secrets temporal-visibility-store, temporal-default-store, ssdsecret, db-secret, rabbitmq-secret, for namespace: $NAMESPACE"
              kubectl create secret generic temporal-visibility-store --from-literal=username=postgres --from-literal=password=network123 -n "$namespace"
              kubectl create secret generic temporal-default-store --from-literal=username=postgres --from-literal=password=network123 -n "$namespace"
              kubectl create secret generic db-secret --from-literal=username=postgres --from-literal=password=network123 -n "$namespace"
              {{- end }}

              echo "Generating the rabbitmq-secret for the namespace: $NAMESPACE"
              kubectl create secret generic rabbitmq-secret --from-literal=username=rabbitmq --from-literal=password=Networks123 -n "$namespace"

              echo "Generating random secrets for Minio, Redis, Mobsf and Encryption for the namespace: $NAMESPACE"
              REDIS_PASS=$(openssl rand -base64 16 | tr -dc 'A-Za-z0-9')
              AES_KEY=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9')

              kubectl create secret generic redis-secret --from-literal=password="$REDIS_PASS" -n "$NAMESPACE"
              kubectl create secret generic ssdsecret --from-literal=AESEncryptionKey="$AES_KEY" -n "$NAMESPACE"

              {{- if .Values.minio.enabled }}
              MINIO_USER=$(openssl rand -base64 16 | tr -dc 'A-Za-z0-9')
              MINIO_PASS=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9')
              kubectl create secret generic minio-secret --from-literal=username="$MINIO_USER" --from-literal=password="$MINIO_PASS" -n "$NAMESPACE"
              {{- end }}
      serviceAccountName: secrets-sa
{{- end }}
