apiVersion: v1
kind: ConfigMap
metadata:
  name: prism-iac
  labels:
    app: ssd
{{ include "ssd.standard-labels" . | indent 4 }}
    component: prism-iac
data:
{{ (tpl (.Files.Glob "config/prism-iac/prism-iac.yaml").AsConfig . ) | indent 2 }}
