apiVersion: v1
kind: ConfigMap
metadata:
  name: snyk-monitor-config
  labels:
    app: ssd
{{ include "ssd.standard-labels" . | indent 4 }}
    component: snyk-monitor
data:
{{ (tpl (.Files.Glob "config/snyk-monitor/config.yaml").AsConfig . ) | indent 2 }}
