apiVersion: v1
kind: Service
metadata:
  name: ssd-shield-processor
  labels:
    app: ssd
    component: ssd-shield-processor
{{ include "ssd.standard-labels" . | indent 4 }}
{{- if .Values.shieldprocessor.serviceAnnotations }}
  annotations:
{{ toYaml .Values.shieldprocessor.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      {{- if eq .Values.k8sServiceType "NodePort" }}
      nodePort: 8080
      {{- end }}
  selector:
    app: ssd
    component: ssd-shield-processor
