source-scan:
  username: 'rabbitmq'
  password: 'Networks123'
  host: rabbitmq-service
  port: 5672
  queue: source-scan
  exchange: echo.events
  bindingKey: source-scan
artifact-scan:
  username: 'rabbitmq'
  password: 'Networks123'
  host: rabbitmq-service
  port: 5672
  queue: artifact-scan
  exchange: echo.events
  bindingKey: artifact-scan
  platformQueues:
    docker: artifact-scan-docker
    gitlab-registry: artifact-scan-gitlab
    general: artifact-scan-general
