apiVersion: v1
kind: ConfigMap
metadata:
  name: hasura-metadata-config
  labels:
    app: ssd
    component: hasura
{{ include "ssd.standard-labels" . | indent 4 }}
data:
{{ (tpl (.Files.Glob "config/hasura/metadata.json").AsConfig . ) | indent 2 }}
