apiVersion: v1
kind: Service
metadata:
  labels:
    app: ssd
    component: ssd-api-mcp
  name: ssd-api-mcp
{{- if .Values.mcpserver.serviceAnnotations }}
  annotations:
{{ toYaml .Values.mcpserver.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  ports:
  - name: sd-api-mcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ssd
    component: ssd-api-mcp
  type: ClusterIP
