apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbomkit-backend
  labels:
    app: ssd
    component: cbomkit-backend
{{ include "ssd.standard-labels" . | indent 4 }}
spec:
  replicas: {{ .Values.cbom.replicaCount }}
  selector:
    matchLabels:
      app: ssd
      component: cbomkit-backend
  template:
    metadata:
      labels:
        app: ssd
        component: cbomkit-backend
{{ include "ssd.standard-labels" . | indent 8 }}
      annotations:
{{- if .Values.cbom.annotations -}}
         {{ toYaml .Values.cbom.annotations | nindent 8 }}
{{- end }}
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - "-c"
            - |
              until nc -z ssd-db 5432; do
                echo "Waiting for PostgreSQL to be ready..."
                sleep 2
              done
              echo "PostgreSQL is ready!"
      containers:
        - name: backend
          image: {{ template "cbom.image" . }}
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 8081
              protocol: TCP
          env:
            - name: CBOMKIT_DB_TYPE
              value: postgresql
            - name: CBOMKIT_DB_JDBC_URL
              value: jdbc:postgresql://{{ .Values.db.host }}:{{ .Values.db.port }}/ssd
            - name: CBOMKIT_PORT
              value: "8081"
            - name: CBOMKIT_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: CBOMKIT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: CBOMKIT_FRONTEND_URL_CORS
              value: http://localhost:8001
            - name: JAVA_OPTS
              value: "-Xmx6g -Xms2g"
        {{- with .Values.cbom.probes }}
        {{- toYaml . | nindent 10 }}
        {{- else }}
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 25
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
        {{- end }}
      {{- with .Values.cbom.resources }}
          resources:
      {{- toYaml . | nindent 12 }}
      {{- end }}
          securityContext: {}
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{- end }}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
