apiVersion: v1
kind: Service
metadata:
  name: cbomkit-backend
  labels:
    app: cbomkit
    component: cbomkit-backend
spec:
  ports:
    - name: api
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: cbomkit
    component: cbomkit-backend
  type: ClusterIP
