appName: AIShield
logLevel: info ## Need to parameterise
showVersion: false
timezone: "America/Los_Angeles" ## Need to parameterise
apiHost: aishield
apiPort: 8090
publicKeyPath: /tools/ssd-public-keys
gatewayPort: 8080
scanResultPath: "/tools/scanResult"
opaHostPort: "http://ssd-opa:8200"
toolChainHostPort: "http://tool-chain:8100"
runtime:
  workerCount: 2
temporal:
  hostPort: ssd-temporal-frontend:7233 ## Check with Ritik
  namespace: ssd-opa
  taskQueue: aishield
  maxConcurrentActivityExecutionSize: 100
  maxConcurrentWorkflowTaskExecutionSize: 100
s3:
  bucketName: ssd-temporal ## Check with Ritik
dgraph:
  internalTokenPath: "/tools/secrets/aishield/token"
  {{- if .Values.dgraph.HA.enabled }}
  graphQLAddr: "http://dgraph-alpha-public:8080/graphql"
  {{- else }}
  graphQLAddr: "http://dgraph-public:8080/graphql"
  {{- end }}
dlvs:
  addr: "http://dlvs:5000"
activityTimeout: "1h"
