apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-gateway-config
  labels:
    app: ssd
{{ include "ssd.standard-labels" . | indent 4 }}
    component: otel-gateway
data:
{{ (tpl (.Files.Glob "config/otel/otel-gateway-config.yaml").AsConfig . ) | indent 2 }}
