apiVersion: v1
kind: Service
metadata:
  name: otel-gateway
  labels:
    app: ssd
    component: otel-gateway
{{ include "ssd.standard-labels" . | indent 4 }}
{{- if .Values.otel.serviceAnnotations }}
  annotations:
{{ toYaml .Values.otel.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  ports:
    - name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: prometheus
      port: 9464
      protocol: TCP
      targetPort: 9464
  selector:
    app: ssd
    component: otel-gateway
