apiVersion: v1
kind: Service
metadata:
  name: ssd-github-code-scan
  labels:
    app: ssd
    component: github-codescan
{{ include "ssd.standard-labels" . | indent 4 }}
{{- if .Values.githubcodescan.serviceAnnotations }}
  annotations:
{{ toYaml .Values.githubcodescan.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  ports:
    - name: ssd-github-code-scan
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: ssd
    component: github-codescan
