---
# Source: ssd/templates/mobsf/mobsf-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mobsf-secret
type: Opaque
data:
  MOBSF_API_KEY: "YzNrOG9PT0ZDZk1SWmdIaU03Z213cEw4R2hXbHJLcVhNeGUzUVBWeHp6OXNhWmZ1c2k3SkEwMGFEOXhleHQ="
