---
# Source: ssd/templates/mobsf/mobsf-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mobsf-service
  labels:
    app: ssd
    component: mobsf
    heritage: "Helm"
    release: "ssd"
    chart: "ssd-2024.12.00"
spec:
  ports:
    - name: mobsf
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: ssd
    component: mobsf
