apiVersion: v1
data:
{{ (tpl (.Files.Glob "config/ssd-aibom/config.aibom.yaml").AsConfig . ) | indent 2 }}
kind: ConfigMap
metadata:
  name: aibom-config
  labels:
    app: ssd
    component: ssd-aibom
{{ include "ssd.standard-labels" . | indent 4 }}
