{{- if .Values.dgraph.HA.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dgraph-sa
{{- if .Values.dgraph.HA.saAnnotations }}
  annotations:
{{ toYaml .Values.dgraph.HA.saAnnotations | indent 4 }}
{{- end }}
{{- end }}
