apiVersion: v1
kind: Service
metadata:
  name: dgraph-public
  labels:
    app: ssd
    component: dgraph
{{- if .Values.dgraph.serviceAnnotations }}
  annotations:
{{ toYaml .Values.dgraph.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  ports:
  - port: 5080
    targetPort: 5080
    name: grpc-zero
  - port: 6080
    targetPort: 6080
    name: http-zero
  - port: 8080
    targetPort: 8080
    name: http-alpha
  - port: 9080
    targetPort: 9080
    name: grpc-alpha
  - port: 8000
    targetPort: 8000
    name: http-ratel
  selector:
    app: ssd
    component: dgraph
