---
# Source: ssd/charts/minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ssd-minio
  labels:
    app: minio
    chart: minio-8.0.9
    release: ssd
    heritage: Helm
type: Opaque
data:


  accesskey: "T2FDUEx3ZmRYNmlGVnl5OGdRY3E="
  secretkey: "S2VZSnpsb1RaaGJPWDJDTWZqOFVONjlSVG1RVURCSUdxWE9iTHRSSw=="
