apiVersion: v1
kind: ConfigMap
metadata:
  name: ssd-shield-gateway-config
  labels:
    app: ssd
{{ include "ssd.standard-labels" . | indent 4 }}
    component: ssd-shield-gateway
data:
{{ (tpl (.Files.Glob "config/ssd-shield-gateway/config.yaml").AsConfig . ) | indent 2 }}
