apiVersion: v1
kind: Service
metadata:
  name: ssd-shield-gateway
  labels:
    app: ssd
    component: ssd-shield-gateway
{{ include "ssd.standard-labels" . | indent 4 }}
{{- if .Values.shieldgateway.serviceAnnotations }}
  annotations:
{{ toYaml .Values.shieldgateway.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  ports:
    - name: grpc
      protocol: TCP
      port: 9443
      targetPort: 9443
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: ssd
    component: ssd-shield-gateway
