rabbitmq:
  username: '{{ .Values.rabbitmq.username }}'
  password: '{{ .Values.rabbitmq.password }}'
  host: rabbitmq-service
  port: 5672
  queue: argo-ssd
  exchange: argo.events
  bindingKey: argo-ssd
  prefetchCount: 50

redis:
  address: {{ .Release.Name }}-redis-master:{{ .Values.redis.port }}
  password: {{ .Values.redis.password }}
  DB: 0
graphql:
  host: http://dgraph-public
  port: 8080

supplychainapi:
  host: http://supplychain-api
  port: 8099
