rabbitmq:
  username: '{{ .Values.rabbitmq.username }}'
  password: '{{ .Values.rabbitmq.password }}'
  host: rabbitmq-service
  port: 5672
  queue: githubactions-ssd
  exchange: githubactions.events
  bindingKey: githubactions-ssd
  prefetchCount: 50

graphql:
  host: http://dgraph-public
  port: 8080

ssdopasvc:
  host: http://ssd-opa
  port: 8200
