apiVersion: v1
kind: Service
metadata:
  labels:
    app: ssd
    component: ssd-rabbitmq
{{ include "ssd.standard-labels" . | indent 4 }}
{{- if .Values.rabbitmq.serviceAnnotations }}
  annotations:
{{ toYaml .Values.rabbitmq.serviceAnnotations | indent 4 }}
{{- end }}
  name: rabbitmq-service
spec:
  type: {{ .Values.RabbitServiceType }}
  ports:
  - name: rabbitmq
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: rabbitmq-mgmt
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: ssd
    component: ssd-rabbitmq
