---
# Source: ssd/templates/supplychain-preprocessor/ssd-secret.yaml
apiVersion: v1
data:
  AESEncryptionKey: T0tQUUswSldTMlRWVFc5RTg2SVdXWU4zVlk0WjM0V0o=
  #approved_build_server: bnVsbA==
  #authorized_artifact_repo: bnVsbA==
  #image_containers: bnVsbA==
  #openAI_creds: bnVsbA==
  #opsmx_creds: bnVsbA==
  #sbom_tool: bnVsbA==
  #semgrep_webApi_token: bnVsbA==
  #sonarQube_creds: bnVsbA==
  #source_code: bnVsbA==
kind: Secret
metadata:
  name: ssdsecret
type: Opaque
