---
# Source: ssd/templates/ssd-opa/ssd-opa-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ssd-opa
  labels:
    app: ssd
    heritage: "Helm"
    release: "ssd"
    chart: "ssd-2024.12.00"
    component: ssd-opa
stringData:
  ssd-opa.yaml: |
    httpListenPort: 8200
    graphQLAddr: http://dgraph-public:8080/graphql
    ssdUrl: https://ssd-gitargo.aoa.oes.opsmx.org
    logLevel: debug
    reScheduler: false
    redis:
      address : ssd-redis-master:6379
      password: 12345sdfa
      db: 0
