{{- if and (eq .Values.installationMode "Helm") .Release.IsInstall -}}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "mobsf-secret") -}}
{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: mobsf-secret
type: Opaque
data:
  mobsfapikey: {{ randAlphaNum 62 | b64enc | quote }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: mobsf-secret
type: Opaque
data:
  mobsfapikey: {{ $existingSecret.data.mobsfapikey }}
{{- end }}
{{- end }}
