apiVersion: v1
kind: Service
metadata:
  name: mobsf-service
  labels:
    app: ssd
    component: mobsf
{{ include "ssd.standard-labels" . | indent 4 }}
{{- if .Values.mobsf.serviceAnnotations }}
  annotations:
{{ toYaml .Values.mobsf.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  ports:
    - name: mobsf
      protocol: TCP
      port: 8000
      targetPort: 8000
      {{- if eq .Values.k8sServiceType "NodePort" }}
      nodePort: 8000
      {{- end }}
  selector:
    app: ssd
    component: mobsf
