{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "mobsf-secret") -}}
{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: mobsf-secret
type: Opaque
data:
  MOBSF_API_KEY: {{ randAlphaNum 62 | b64enc | quote }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: mobsf-secret
type: Opaque
data:
  MOBSF_API_KEY: {{ $existingSecret.data.MOBSF_API_KEY }}
{{- end }}
