apiVersion: v2
name: ssd
version: "2025.12.00"
appVersion: "2025.12.00"
description: "OpsMx Secure Software Delivery for CI/CD"
icon: https://raw.githubusercontent.com/OpsMx/enterprise-spinnaker/master/img/opsmx.png
maintainers:
- email: saiteja.katabhatina@opsmx.io
  name: Sai Teja K
keywords:
  - OpsMx
  - SSD
home: https://www.opsmx.com/
dependencies:
  - name: dex
    version: 0.15.3
    condition: ssdgate.installDex
  - name: minio
    version: 16.0.10
    condition: minio.enabled
  - name: redis
    version: 21.1.11
    condition: installRedis
  - name: temporal
    version: 0.63.0
    condition: temporal.enabled

