imageCredentials:
  repoUrl: docker.io
  # Update this is using a private repo such as ACR, ECR, GCR, JFrog, etc.
  registry: opsmx11

ui:
  image:
    tag: "73f36bd72-809"
  serviceAnnotations:
    awsAnnotationsGo: HERE
toolchain:
  image:
    tag: "7e38bcf-110"
  #securityContext:
  #  fsGroup: 1000
  #  runAsUser: 1000
  #  runAsGroup: 1000
ssdgate:
  image:
    repository: ssd-gate
    tag: "e3acfc6-106"
ssdopa:
  image:
    tag: "eca334d-155"
supplychainpreprocessor:
  image:
    tag: "cc339e7-96"
  #securityContext:
  #  readOnlyRootFilesystem: false
  #  runAsNonRoot: true
supplychainapi:
  image:
    tag: "51c3303-803"
tokenmachine:
  image:
    tag: "99eb752-36"

sourcescan:
  image:
    repository: source-scan
    tag: "ee0c3c2-28"

snykmonitor:
  image:
    repository: snyk-monitor
    tag: "e89fbfb-2"
    pullPolicy: IfNotPresent

mobsf:
  image:
    repository: mobsf
    tag: "v4.1.3"

projectmonitor:
  image:
    repository: project-monitor
    tag: "61324b0-13"

ssdrescheduler:
  image:
    repository: ssd-rescheduler
    tag: "946b56e-1"

artifactscan:
  image:
    repository: artifact-scan
    tag: "f759bfe-2"
