imageCredentials:
  repoUrl: docker.io
  # Update this is using a private repo such as ACR, ECR, GCR, JFrog, etc.
  registry: opsmx11

ui:
  image:
    tag: "620ba4b7f-28"
  serviceAnnotations:
    awsAnnotationsGo: HERE
toolchain:
  image:
    tag: "b18dd75-10"
  #securityContext:
  #  fsGroup: 1000
  #  runAsUser: 1000
  #  runAsGroup: 1000
ssdgate:
  image:
    repository: ssd-gate
    tag: "94b5f25-18"
ssdopa:
  image:
    tag: "b1668f2-12"
supplychainpreprocessor:
  image:
    tag: "e065ed8-12"
  #securityContext:
  #  readOnlyRootFilesystem: false
  #  runAsNonRoot: true
supplychainapi:
  image:
    tag: "25a9c27-55"
tokenmachine:
  image:
    tag: "99eb752-9"
