imageCredentials:
  repoUrl: docker.io
  # Update this is using a private repo such as ACR, ECR, GCR, JFrog, etc.
  registry: opsmx11

ui:
  image:
    tag: "32b9d9372-755"
  serviceAnnotations:
    awsAnnotationsGo: HERE
toolchain:
  image:
    tag: "d6c84ca-97"
  #securityContext:
  #  fsGroup: 1000
  #  runAsUser: 1000
  #  runAsGroup: 1000
ssdgate:
  image:
    repository: ssd-gate
    tag: "e3acfc6-106"
ssdopa:
  image:
    tag: "5c77e44-143"
supplychainpreprocessor:
  image:
    tag: "f8748b7-93"
  #securityContext:
  #  readOnlyRootFilesystem: false
  #  runAsNonRoot: true
supplychainapi:
  image:
    tag: "d31e643-701"
tokenmachine:
  image:
    tag: "99eb752-36"

sourcescan:
  image:
    repository: source-scan
    tag: "77d1423-17"

snykmonitor:
  image:
    repository: snyk-monitor
    tag: "dbc7256-1"
    pullPolicy: IfNotPresent

mobsf:
  image:
    repository: mobsf
    tag: "v4.1.3"

projectmonitor:
  image:
    repository: project-monitor
    tag: "20b3822-5"
