imageCredentials:
  repoUrl: docker.io
  # Update this is using a private repo such as ACR, ECR, GCR, JFrog, etc.
  registry: opsmx11

ui:
  image:
    tag: "6cf4c3abf-182"
  serviceAnnotations:
    awsAnnotationsGo: HERE
toolchain:
  image:
    tag: "56f6c0f-127"
  #securityContext:
  #  fsGroup: 1000
  #  runAsUser: 1000
  #  runAsGroup: 1000
ssdgate:
  image:
    repository: ssd-gate
    tag: "7688913-90"
ssdopa:
  image:
    tag: "762219b-116"
supplychainpreprocessor:
  image:
    tag: "09c0b90-105"
  #securityContext:
  #  readOnlyRootFilesystem: false
  #  runAsNonRoot: true
supplychainapi:
  image:
    tag: "02198c3-1804"
tokenmachine:
  image:
    tag: "eca0aed-2"
