####################################################
ssdgate:
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 1500Mi
      cpu: 1500m
  #resources: {}
  #  requests:
  #    memory: 500Mi
  #    cpu: 500m
  #  limits:
  #    memory: 1500Mi
  #    cpu: 1500m
###############################################################################
db:
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 1500Mi
      cpu: 1500m

  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 1
    tcpSocket:
      port: 5432
    timeoutSeconds: 1

####################################################
toolchain:
  replicaCount: 1
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 1500Mi
      cpu: 1500m
  ## During the scanning if the repo need to clone only once set to true
  cloneRepoOnce: false
####################################################
supplychainpreprocessor:
  replicaCount: 1
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 1500Mi
      cpu: 1500m

  #resources: {}
  #  requests:
  #    memory: 500Mi
  #    cpu: 500m
  #  limits:
  #    memory: 1500Mi
  #    cpu: 1500m
####################################################
ssdopa:
  replicaCount: 1
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 1500Mi
      cpu: 1500m

  #resources: {}
  #  requests:
  #    memory: 500Mi
  #    cpu: 500m
  #  limits:
  #    memory: 1500Mi
  #    cpu: 1500m

####################################################
supplychainapi:
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  #resources: {}

  #  requests:
  #    memory: 500Mi
  #    cpu: 500m
  #  limits:
  #    memory: 1500Mi
  #    cpu: 1500m
######################################################
tokenmachine:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  #resources: {}

  #  requests:
  #    memory: 500Mi
  #    cpu: 500m
  #  limits:
  #    memory: 1500Mi
  #    cpu: 1500m
###############################################################################
## Details of rabbitmq message bus image for SSD
##
rabbitmq:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  #resources: {}

  #  requests:
  #    memory: 500Mi
  #    cpu: 500m
  #  limits:
  #    memory: 1500Mi
  #    cpu: 1500m
###############################################################################
## Values of SSD UI
ui:
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 1500Mi
      cpu: 1500m

  #resources: {}

  #  requests:
  #    memory: 500Mi
  #    cpu: 500m
  #  limits:
  #    memory: 1500Mi
  #    cpu: 1500m

#############################################################################
mobsf:
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  #resources: {}
  #  requests:
  #    memory: 500Mi
  #    cpu: 500m
  #  limits:
  #    memory: 1500Mi
  #    cpu: 1500m
##############################################################################
##
zap:
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  #resources: {}

  #  requests:
  #    memory: 500Mi
  #    cpu: 500m
  #  limits:
  #    memory: 1500Mi
  #    cpu: 1500m
###############################################################################################
###  Redis Configuration
###############################################################################################
## Details of redis-master image for OES
redis:
  master:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m

#########################################################################
temporal:
  server:
    replicaCount: 1
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    frontend:
      resources: {}
      podDisruptionBudget: {}
    history:
      resources: {}
      podDisruptionBudget: {}
    worker:
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      podDisruptionBudget: {}
    matching:
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      podDisruptionBudget: {}


  web:
    replicaCount: 1
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  admintools:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    podDisruptionBudget: {}
