{{- if not (lookup "v1" "Secret" .Release.Namespace "rabbitmq-secret") }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  rabbitmqPassword: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}
