---
# Source: ssd/templates/ssd-ui/ssd-ui-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssd
    component: ui
    heritage: "Helm"
    release: "ssd"
    chart: "ssd-2024.12.00"
  name: ssd-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssd
      component: ui
  template:
    metadata:
      annotations:
        checksum/configmap: 1e0348c6111d4ffe453c933e9f2088469caaeeaaa14268cfa4de8f04ee366c96
      labels:
        app: ssd
        component: ui
    spec:
      containers:
      - image: quay.io/opsmxpublic/ssd-ui:2024-12-00
        name: ssd-ui
        env:
        envFrom:
        - configMapRef:
            name: ssd-proxy-certs
            optional: true
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: config-dir
          mountPath: /var/www/html/ui/assets/config/app-config.json
          subPath: app-config.json
        - name: config-dir
          mountPath: /var/www/html/ui/assets/config/help-text.json
          subPath: help-text.json
        - name: config-dir
          mountPath: /var/www/html/ui/assets/config/integrators-config.json
          subPath: integrators-config.json
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          subPath: nginx.conf
        - mountPath: /usr/local/share/ca-certificates
          name: custom-certs
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /ui/indexl.html
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        securityContext:
      
          allowPrivilegeEscalation: false
      volumes:
      - configMap:
          defaultMode: 420
          name: ssd-ui-config
        name: config-dir
      - name: custom-certs  # Optional: In case we are using any customer-specific custom CAs
        configMap:
          defaultMode: 420
          items:
          - key: ca.crt
            path: ca.crt
          optional: true
          name: customer-custon-ca
      - configMap:
          defaultMode: 420
          name: ssd-ui-nginxconf
        name: nginx-config
      - name: ssd-proxy-certs
        configMap:
          defaultMode: 420
          optional: true
          name: ssd-proxy-certs
