receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  otlp:
    endpoint: "http://otel-gateway:4317"
    tls:
      insecure: true

    debug:
      verbosity: detailed

    prometheus:
      endpoint: "0.0.0.0:9464"
      enable_open_metrics: true
      metric_expiration: 5m
      resource_to_telemetry_conversion:
        enabled: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,debug,prometheus]
