apiVersion: v1
kind: Service
metadata:
  name: ssd-rescheduler
  labels:
    app: ssd
    component: ssd-rescheduler
{{ include "ssd.standard-labels" . | indent 4 }}
{{- if .Values.ssdrescheduler.serviceAnnotations }}
  annotations:
{{ toYaml .Values.ssdrescheduler.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  ports:
    - name: ssd-rescheduler
      protocol: TCP
      port: 8010
      targetPort: 8010
      {{- if eq .Values.k8sServiceType "NodePort" }}
      nodePort: 8010
      {{- end }}
  selector:
    app: ssd
    component: ssd-rescheduler
