apiVersion: v1
kind: ConfigMap
metadata:
  name: ssd-rescheduler-config
  labels:
    app: ssd
{{ include "ssd.standard-labels" . | indent 4 }}
    component: ssd-rescheduler
data:
{{ (tpl (.Files.Glob "config/ssd-rescheduler/ssd-rescheduler.yaml").AsConfig . ) | indent 2 }}
