apiVersion: v1
data:
{{ (tpl (.Files.Glob "config/opsmx-assistant/app.config.json").AsConfig . ) | indent 2 }}
kind: ConfigMap
metadata:
  name: opsmx-assistant-config
  labels:
    app: ssd
    component: opsmx-assistant
{{ include "ssd.standard-labels" . | indent 4 }}
