apiVersion: v1
kind: Service
metadata:
  name: opsmx-assistant
  labels:
    app: ssd
    component: opsmx-assistant
{{ include "ssd.standard-labels" . | indent 4 }}
{{- if .Values.opsmxassistant.serviceAnnotations }}
  annotations:
{{ toYaml .Values.opsmxassistant.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      {{- if eq .Values.k8sServiceType "NodePort" }}
      nodePort: 8080
      {{- end }}
  selector:
    app: ssd
    component: opsmx-assistant
