deploymentRetry: {{ .Values.ssdrescheduler.deploymentRetry }} # Param to determine whether a failed deployment is to be retried
deploymentRetryInterval: {{ .Values.ssdrescheduler.deploymentRetryInterval }} # unit is minutes. Example if 10 given every 10mins it will retry failed deployments. 5 deployment to be retired a time
maxRetryOfDeployment: {{ .Values.ssdrescheduler.maxRetryOfDeployment }} #max number of times deployment is to be retried
rescheduler: {{ .Values.ssdrescheduler.rescheduler }} # Rescheduler to reanalyze images in current deployment & recent adhoc scans of source, artifact & sbom
reScheduleDays: 1
deploymentRetryBatchCount: {{ .Values.ssdrescheduler.deploymentRetryBatchCount }}
reScheduleTime: "15:41"
ossScheduler: true
ossSchedulerInterval: {{ .Values.ssdrescheduler.ossSchedulerInterval }} #interval minutes default is 30minutes
{{- if .Values.dgraph.HA.enabled }}
graphQLAddr: "http://dgraph-alpha-public:8080/graphql"
{{- else }}
graphQLAddr: "http://dgraph-public:8080/graphql"
{{- end }}
ssdOpaAddr: "http://ssd-opa:8200"
logLevel: "{{ .Values.ssdrescheduler.logLevel }}"
httpListenPort: 8010 #default & optional
recommendedVersionWatcher: true # default false
recommendedVersionWatchInterval: 2 # default
recommendedVersionReanalyze: true # default false
recommendedVersionReanalyzeTime: "00:00" # default
recommendedVersionStaleDays: 10 # default
ssdVulnAddr: "http://212.2.240.29:8900" # default
