signingKeys:
  publicKeyConfigmapName: ssd-public-keys
  secretKeyNamePrefix: jwtrsa
  regenerateInterval: 15768000
  keyLengthBits: 2048
managedSecrets:
  regenerateInterval: {{ .Values.tokenmachine.regenerateInterval }} # seconds
  secrets:
    - name: ssd-gate-token # the k8s name for this token
      serviceName: ssd-gate
      authorizations:
        - generate-user-token
    - name: supplychain-api-token
      serviceName: supplychain-api
      authorizations:
        - generate-serviceaccount-token
        - access-dgraph
    - name: ssd-opa-token
      serviceName: ssd-opa
      authorizations:
        - access-dgraph
    - name: tool-chain-token
      serviceName: tool-chain
      authorizations:
        - access-dgraph
    - name: iacscan-service-token
      serviceName: iacscan-service
      authorizations:
        - access-dgraph
    - name: supplychain-preprocessor-token
      serviceName: supplychain-preprocessor
      authorizations:
        - access-dgraph
    - name: snyk-monitor-secret
      serviceName: snyk-monitor
      authorizations:
        - access-dgraph
    - name: source-scan-token
      serviceName: source-scan-service
      authorizations:
        - access-dgraph
    - name: project-monitor-token
      serviceName: project-monitor
      authorizations:
        - access-dgraph
    - name: ssd-rescheduler-token
      serviceName: ssd-rescheduler
      authorizations:
        - access-dgraph
    - name: artifact-scan-token
      serviceName: artifact-scan
      authorizations:
        - access-dgraph
    - name: ssd-audit-service-token
      serviceName: ssd-audit-service
      authorizations:
        - access-dgraph
    - name: hasura-token
      serviceName: hasura
      authorizations:
        - access-dgraph
    - name: aishield-token
      serviceName: aishield
      authorizations:
        - access-dgraph
    - name: ssd-notification-token
      serviceName: ssd-notification
      authorizations:
        - access-dgraph
    - name: prism-iac-token
      serviceName: prism-iac
      authorizations:
        - access-dgraph
    - name: checkmarx-poller-token
      serviceName: checkmarx-poller
      authorizations:
        - access-dgraph
    - name: ssd-api-mcp-token
      serviceName: ssd-api-mcp
      authorizations:
        - access-dgraph
    - name: ssd-shield-gateway-token
      serviceName: ssd-shield-gateway
      authorizations:
        - access-dgraph
    - name: hbom-generator-token
      serviceName: hbom-generator
      authorizations:
        - access-dgraph
