---
# Source: ssd/templates/ssd-gate/ssd-initial-password.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ssd-initial-password
type: Opaque
data:
  ADMIN_PASSWORD: "c3hGeFlKaENhR212c0F6Sg=="
  USER1_PASSWORD: "aVdCajNMNVNzUUxuRmpFeA=="
