---
# Source: ssd/charts/temporal/templates/admintools-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ssd-temporal-admintools
  labels:
    app.kubernetes.io/name: temporal
    helm.sh/chart: temporal-0.22.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: ssd
    app.kubernetes.io/version: 1.20.3
    app.kubernetes.io/component: admintools
    app.kubernetes.io/part-of: temporal
spec:
  type: ClusterIP 
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh

  selector:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: ssd
    app.kubernetes.io/component: admintools
