---
# Source: ssd/charts/temporal/templates/server-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ssd-temporal-default-store
  labels:
    app.kubernetes.io/name: temporal
    helm.sh/chart: temporal-0.22.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: ssd
    app.kubernetes.io/version: 1.20.3
    app.kubernetes.io/part-of: temporal
type: Opaque
data:
  password: "bmV0d29ya3MxMjM="
---
# Source: ssd/charts/temporal/templates/server-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ssd-temporal-visibility-store
  labels:
    app.kubernetes.io/name: temporal
    helm.sh/chart: temporal-0.22.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: ssd
    app.kubernetes.io/version: 1.20.3
    app.kubernetes.io/part-of: temporal
type: Opaque
data:
  password: "bmV0d29ya3MxMjM="
