---
# Source: ssd/charts/temporal/templates/web-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssd-temporal-web-config
  labels:
    app.kubernetes.io/name: temporal
    helm.sh/chart: temporal-0.22.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: ssd
    app.kubernetes.io/version: 1.20.3
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: temporal
data:
  config.yml: |
    auth:
      enabled: false
    routing:
      issue_report_link: https://github.com/temporalio/web/issues/new/choose
