apiVersion: v1
kind: ConfigMap
metadata:
  name: hbom-generator-config
  labels:
    app: ssd
{{ include "ssd.standard-labels" . | indent 4 }}
    component: hbom
data:
{{ (tpl (.Files.Glob "config/hbom/config.yaml").AsConfig . ) | indent 2 }}
