apiVersion: v1
kind: Service
metadata:
  name: hbom-generator
  labels:
    app: ssd
    component: hbom-generator
{{ include "ssd.standard-labels" . | indent 4 }}
{{- if .Values.hbom.serviceAnnotations }}
  annotations:
{{ toYaml .Values.hbom.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  ports:
  - name: hbom-generator
    protocol: TCP
    port: 8090
    targetPort: 8090
  selector:
    app: ssd
    component: hbom-generator
  type: ClusterIP
