apiVersion: v1
kind: ConfigMap
metadata:
  name: ssd-notification-config
  labels:
    app: ssd
{{ include "ssd.standard-labels" . | indent 4 }}
    component: ssd-notification
data:
{{ (tpl (.Files.Glob "config/ssd-notification-service/ssd-notification.yaml").AsConfig . ) | indent 2 }}
