apiVersion: v1
kind: Service
metadata:
  name: supplychain-api
  labels:
    app: ssd
    component: supplychain-api
{{ include "ssd.standard-labels" . | indent 4 }}
{{- if .Values.supplychainapi.serviceAnnotations }}
  annotations:
{{ toYaml .Values.supplychainapi.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  ports:
    - name: supplychain-api
      protocol: TCP
      port: 8099
      targetPort: 8099
      {{- if eq .Values.k8sServiceType "NodePort" }}
      nodePort: 8099
      {{- end }}
  selector:
    app: ssd
    component: supplychain-api
