httpListenPort: 8100
{{- if .Values.dgraph.HA.enabled }}
graphQLAddr: http://dgraph-alpha-public:8080/graphql
{{- else }}
graphQLAddr: http://dgraph-public:8080/graphql
{{- end }}
cloneRepoOnce: {{ .Values.toolchain.cloneRepoOnce }}
logLevel: {{ .Values.toolchain.logLevel }}
ossSvc: http://34.60.164.173:8070
ssdVuln: http://212.2.244.234:8900
mobsfClentAddr: http://mobsf-service:8000
otelAddr: localhost:4317
otelInterval: {{ .Values.otel.interval }}
