---
# Source: ssd/templates/supplychain-api/supplychain-api-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: supplychain-api
  labels:
    app: ssd
    heritage: "Helm"
    release: "ssd"
    chart: "ssd-2024.12.00"
    component: supplychain-api
stringData:
  app-config.yaml: |
    ssdIngress: https://ssd-gitargo.aoa.oes.opsmx.org
    detectorImage: quay.io/opsmxpublic/kubernetes-detector:v1.0.2
    kubescapeImage: quay.io/opsmxpublic/kubescape-service:v0.0.1
    tokenMachine:
        host: http://token-machine
        port: 8050
    opsMxSvc: https://ssd-gitargo.aoa.oes.opsmx.org
    ssdOpa: http://ssd-opa:8200
    redis: redis://:12345sdfa@ssd-redis-master:6379
    graphqlsvc:
        host: http://dgraph-public
        port: 8080
    postgresql:
        ssd:
          connectString: host=ssd-db user='postgres'  password='networks123' database=ssddb port=5432
    toolchain:
        host: http://tool-chain
        port: 8100
    spinnaker:
        rabbitmq:
          username: 'rabbitmq'
          password: 'Networks123'
          host: rabbitmq-service
          port: 5672
          queue: preview-saas-ssd
          #queue: isd-to-preview-saas
          exchange: echo.events
          bindingKey: preview-saas-ssd
