apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tool-chain
spec:
  accessModes:
    - {{ .Values.toolchain.persistence.accessMode }}
  {{- if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass }}
  {{- end }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.toolchain.persistence.size }}
